### ISSUE TITLE
Suggestion/Help with Artifacts mod

### ISSUE THREAD

**Issue by crafting-Aaron** [AllenSeitz/DimDungeons#15]
I have not tested this yet but it appears the artifact mod by default includes the campsite structures in modded dimensions. I wonder if this would overlap the dungeons in this dimension. I feel like a smooth compatibility between the two would be great or instead knowing how I can add the mimic chest mob to spawn at random in dungeon rooms.

**Comment by AllenSeitz** [comment]
I've played just a bit with Artifacts, and I don't think campsites would appear in the dungeon dimension. I'm using a custom chunk generator (to implement my void world) that also basically bans structures.

I had a problem with a previous version of this mod where other mods would "helpfully" add structures to my dimension and then the player would get stuck. For example, a campsite might spawn in a doorway. Or Better Caves would add a lavafall in the middle of the void where it can't be seen and create a bunch of lag for no reason. (Tangent, I wish worldgen mod developers would stop looping over every custom dimension and adding their features where it doesn't make sense.)

For Artifacts I'll make it so that any of the chests which pull from chestloot_lucky can randomly be a mimic! I'll save this ticket to remind me to do that.

**Comment by AllenSeitz** [comment]
Mimics can appear in place of lucky chests as of the most recent version. Thanks for the suggestion!
