### ISSUE TITLE
Treasure Room Crash

### ISSUE THREAD

**Issue by WenXin20** [AllenSeitz/DimDungeons#17]
`Minecraft v1.16.5`
`Forge v36.0.7`
`Dim Dungeons v1.081`

I was trying the mod out in creative when I found when of the treasure rooms. It is the room with two levers, one with lava above it, the other with water above it that would meet to form cobblestone above the double chest. But after pulling the lever, my game crashed client-side while connected to my server.
[Crash Report](https://gist.github.com/WenXin20/489364ec5336344a289ef944abb81bca)

**Comment by AllenSeitz** [comment]
I couldn't replicate this without optifine. But I don't think optifine is to blame.

If you build a similar setup in the Overworld, does that crash? Dimensional Dungeons is fairly vanilla. There's nothing in that room that you can't build yourself. Nothing unusual or proprietary. I'm thinking it has to do with the liquids though, and the shaders. Something about moving them with the piston heads and then creating new flowing blocks maybe.

For reference the room name is deathtrap_1. (I know, silly name. Apparently I failed at building a death trap.) So if you want to you can give yourself a structure block and load structure dimdungeons:deathtrap_1. That will let you replicate the setup for study in other dimensions and in other worlds. Please let me know  if you learn more.

**Comment by WenXin20** [comment]
Alright, I was able to replicate the crash in the overworld simply by placing down a piston and having push a light blue stained glass block. Any idea what could cause this crash? Maybe Quark?

**Comment by AllenSeitz** [comment]
Quark is possible, but I think unlikely. AFAIK Quark doesn't mess with the rendering pipeline? If you think it might be Quark try turning off features related to pistons or light sources.

I have a hunch that there's something about lightning or shaders causing it. Because the piston head extension is a weird transparent block, and stained glass is a normal translucent block, so something weird could be happening there?

Thank you for the work you've put into replicating this. It's interesting (and relieving) that it's any piston and stained glass.

**Comment by AllenSeitz** [comment]
The #1 Quark feature to test would be "pistons push tile entities" I think. Even though stained glass is not a tile entity.

**Comment by WenXin20** [comment]
It still crashed. https://gist.github.com/WenXin20/3b118b33bad4d92e6efd797a30117d12

**Comment by WenXin20** [comment]
Ok, it looks like it is the ctm mod causing the crash.

**Comment by AllenSeitz** [comment]
Thank you again for finding the exact cause. I am much relieved.

**Comment by WenXin20** [comment]
No problem!
