### ISSUE TITLE
[1.16.5] Portal not forming

### ISSUE THREAD

**Issue by faeldray** [AllenSeitz/DimDungeons#29]
I've updated from v1.12 to v1.13 of the mod and I can't get the portal to appear. I don't think it's an issue with the portal build itself, this is what it looks like. And I have a portal key that's been activated.

![2021-07-29_13 04 58](https://user-images.githubusercontent.com/967709/127542971-ea602d9a-793f-4082-b8b0-b15bd8414a25.png)

I did notice this error in the latest.log whenever I try to activate the portal so hopefully that will help.

https://gist.github.com/faeldray/97342773caca48aefa50f6c1745ac0b9

Edit: Just wanted to add if I downgrade to v1.12 again, everything works fine.

**Comment by AllenSeitz** [comment]
Uh oh. It crashed while generating a theme key in a random monster's off hand. What is in your server config?

**Comment by faeldray** [comment]
Do you mean in `defaultconfigs/dimdungeons-server.toml`? [Here's the file](https://gist.github.com/faeldray/97342773caca48aefa50f6c1745ac0b9#file-dimdungeons-server-toml). The only thing I changed in there is the breaking whitelist, to add the graves from Corail Tombstone.

**Comment by AllenSeitz** [comment]
That looks perfect. I am very worried right now.

**Comment by faeldray** [comment]
Oh no, that's not good! I did just test the mod in a very small pack (just JEI, TheOneProbe, and Xaero's World/mini map) and I didn't get any errors. So it seems to be a mod conflict. I'll try to do some tests with different mods from my pack and see if I can isolate the issue.

**Comment by AllenSeitz** [comment]
I just uploaded 1.13.1 to CurseForge which fixes two different crash bugs. One related to stale configs and me trying to overwrite existing values with newer default values. (Which I think is the problem you're having.) And the second was that I listed Forge 36.0.1 as the minimum required version, yet it would crash if you didn't have at least 36.2.0 installed.

**Comment by faeldray** [comment]
I haven't had a chance to test for conflicts in my pack (it has a lot of mods >.>), but I did try out 1.13.1. I even deleted dimdungeons-client.toml and dimdungeons-common.toml just to make sure those weren't a problem. Unfortunately I still got the same error: https://gist.github.com/faeldray/c4786269a6174d78007c70b012641398

**Comment by AllenSeitz** [comment]
This is interesting. Here are the top 3 lines of where it crashed.

at net.minecraft.entity.EntityType.handler$zgl000$spawnFromItemStack(EntityType.java:636) ~[?:?] FROM
at net.minecraft.entity.EntityType.func_220331_a(EntityType.java:313) ~[?:?] FROM
at com.catastrophe573.dimdungeons.structure.DungeonPlacementLogicBasic.spawnEnemyHere (line 397)

So my code called vanilla EntityType.spawn(). (That's what func_220331_a is.) And then that function called something else and crashed.

Here's my code that calls EntityType.spawn()

396:	EntityType<?> entitytype = EntityType.byString(resourceLocation).orElse(EntityType.CHICKEN);
397:	Entity mob = entitytype.spawn((ServerWorld) world, null, null, pos, SpawnReason.STRUCTURE, true, true);

So I'm definitely not passing a null entity type. First, it turns out that if the list of mobs in the config is empty that it would've crashed sooner. (Oops.) So actually that "or else just spawn a minecraft:chicken" thing never happens. At this point I have to have a valid resource location probably pointing to a minecraft:zombie or a minecraft:husk. So I'm kind of out of ideas here. I can't replicate the crash either.

**Comment by faeldray** [comment]
Okay, I've managed to find the cause. It's from the [Forgery](https://www.curseforge.com/minecraft/mc-mods/forgery) mod, specifically the [cracking spawn eggs tweak](https://unascribed.com/fabrication/#tweaks.cracking_spawn_eggs). If only that feature from the mod is turned on, that causes the error. I'm guessing it replaces the default spawn egg behaviour somehow? I'm honestly fine with turning that off, it's just a cosmetic thing anyways. I don't know if you think it's worth changing your code over.

**Comment by AllenSeitz** [comment]
Thank you for finding this! That is a very special case.

The only place I use spawn eggs is inside dispensers. But I don't think that wouldn't cause this, since the dispensers aren't being triggered when the dungeon is created. (I don't think.) But do report this to the author of Forgery.

**Comment by faeldray** [comment]
Does [this](https://github.com/unascribed/Fabrication/issues/258) look like the same error? I'm not familiar with Java so I can only guess. If it is the same, it looks like a fix is coming out soon.

**Comment by AllenSeitz** [comment]
Not quite the same. Although the fix might still fix both.
