### ISSUE TITLE
DimDungeons not generating outside dimension and spamming logs 

### ISSUE THREAD

**Issue by TelepathicGrunt** [AllenSeitz/DimDungeons#3]
I'm creating a mod that imports features from all biomes and I noticed the DimDungeons does not get added to my mod's dimension. Instead, it seems there's an unneeded dimension check in the dungeon features' Place methods and as a result, it spams the logs with this lol
![image](https://user-images.githubusercontent.com/40846040/75193239-cba0b400-5723-11ea-8575-94794d479845.png)

The solution is to remove the dimension checks and add DimDungeons only to the biomes that spawn in DimDungeon's dimension to make DimDungeons more mod friendly. These kinds of error checking doesn't add extra functionality and instead, makes it less compatible with mods that want to handle other mod's stuff.

Still, the DimDungeon dimension is awesome! :)

**Comment by AllenSeitz** [comment]
I think what you need is a new feature, something like a dimdungeons:basic_dungeon_worldgen_safe version. And in this new java class the y-coordinate of the structure would not be hardcoded at 50. And the portal blocks and any obsidian touching them would be replaced with minecraft:air instead of dimdungeons:block_gold_portal. That would create a door. And then maybe a system to control structure rarity like vanilla strongholds? Among other potential changes.

**Comment by TelepathicGrunt** [comment]
Ah that makes sense. The dimension isn't exactly suppose to be balanced at all so complete obliteration is fine in my book lmao. But yeah, I'll see about doing a new feature to work with your mod if possible.

**Comment by AllenSeitz** [comment]
Actually if you're still interested I have a new idea.

My idea still involves creating a new feature. This feature would behave similar to a vanilla shipwreck in the sense that it would spawn at random locations and place a single simple structure.

But the twist is that it spawns single rooms from Dimensional Dungeons! This solves all the problems with spawning whole dungeons and I think seeing single, random, floating rooms scattered around this chaos dimension would be even more on theme!

If you look in the resources folder each room is already implemented as a single structure. They have names such as "dimdungeons:deadend_1" and "dimdungeons:entrance_5". It should be pretty easy to just randomly throw those down anywhere with no connections. And each room was designed to be self contained.

The one catch is that you would probably also want to copy my Data Block handling function so that the chests are assigned loot tables, monsters are spawned, and so forth. Or not! You can also replace those things with anything you want.

**Comment by TelepathicGrunt** [comment]
Oh that's a good idea, thanks! I'll try that out when I get a chance!

**Comment by TelepathicGrunt** [comment]
Thank you so much! I was able to add direct support for your mod and got all the dungeons to spawn nicely! (they don't connect perfectly but it is good enough as I have it where a patch of dungeons will use 4 way dungeons in a checker pattern to maximize connected rooms without needing to resort to making an complicated class to do connections)

I made sure to add a link to your curseforge page of your mod in my mod's page. :)
https://www.curseforge.com/minecraft/mc-mods/worldblender

And I just realized this isn't really any issue report anymore so you can close this lol
