### ISSUE TITLE
Adding new blocks for key activation

### ISSUE THREAD

**Issue by Asveste** [AllenSeitz/DimDungeons#30]
The mod End Remastered adds a new way to enter the end. The problem is, this also comes with a new block for the end portal, thus making it impossible to enter any Dimensional Dungeon. Is there a way to register the modded end portal frame to be able to activate keys?

**Comment by AllenSeitz** [comment]
It always has since about a year ago. I mention this on the mod page too.

**Comment by AllenSeitz** [comment]
I mean, let me know if it's not working. If they changed their block id or something. Target the top of the core block, not the eye blocks.

And actually there is the key inscribing station too. But E:R should be supported even going as far back as 1.14.

**Comment by Asveste** [comment]
Tried it again right now and not working, maybe they changed the block ID as you said? It's currently "endrem:ancient_portal_frame"

**Comment by AllenSeitz** [comment]
Yup. It used to be end_creator and end_creator_activated. I'll make a quick 1.13.2 to address this.

**Comment by AllenSeitz** [comment]
Oh wait, no, it's still the same. I just checked the latest version of their source code. Like I said, make sure you're looking at the core block of the frame, not any of the eye blocks. There's room for 11 eyes and one core. Hit the top center of the core block with the key.

**Comment by AllenSeitz** [comment]
Final answer: you're using an unreleased beta of End Remastered 4.0. My mod is still compatible with the most recent release, 3.6.

I'm surprised that they took the bold step of changing their portal blocks. I agree with their design decisions, but this does mean that everyone who upgrades is going to have a bunch of castles and dungeons without portal frames! Wow. They should do that for 1.17, not for an intermediate 1.16.5 release.

I've already made the trivial change in my code, but I'm not going to rush 1.13.2 since they're still in beta.

In the meantime you can still save your beta world. There's an item in my mod called the Key Inscribing Station. (The item id is dimdungeons:block_key_charger.) It does what it says. You can either cheat a few into your world or make your own crafting recipe for it.

**Comment by Asveste** [comment]
I agree with you that they should've done the step of redoing the portal blocks in a bigger update such as 1.17 or 1.18.

As you said, better don't rush the 1.13.2 version. For now I'm just going to make a quick recipe with KubeJS for the Key Inscribing Station.

Nonetheless I must thank you for taking the time to figure this all out and writing such a detailed response.
