### ISSUE TITLE
player stuck in room 

### ISSUE THREAD

**Issue by KnightNightV2** [AllenSeitz/DimDungeons#37]
player on my server was going through a dungeon and a room closed him into a small space with no buttons or levers to get out and he obviously cant mine out. how do you suggest we get pass this? how do I edit the black and white list to let him mine out?

**Comment by AllenSeitz** [comment]
The easiest way to get a stuck player out would be to /give them an item called a Homeward Pearl. (dimdungeons:item_homeward_pearl). This item is a single use, craftable, consumable that will return a player to the entrance of the current dungeon.

If you're running an older version of the mod that doesn't have this item (like maybe Minecraft 1.15) then I guess just teleport the player to your current coordinates. (TP to them, use spectator to find a nice safe spot, then tp them to you.)

Designing rooms so that players can't get stuck is a top priority of mine. So if you the time please, what happened? Sometimes mod interactions or oversights on my part can create a problem.

**Comment by AllenSeitz** [comment]
Actually this room is broken in most versions of 1.18. I will release a fix as soon as possible.

**Comment by AllenSeitz** [comment]
Fixed in 1.13.4. I'm sorry about that. I seems like whenever a save a room with dispensers there is a chance for the dispensers to save empty. And I can't figure out why but it seems to be inconsistent. I'll have to be careful which rooms I update in this version.
