### ISSUE TITLE
Portal not working "worldIn" is null" 

### ISSUE THREAD

**Issue by Phaetonnz** [AllenSeitz/DimDungeons#38]
We've got this mod installed on Minecraft 1.18.1 local server but when we try to open the portal nothing happens.

The server is showing this error message

"Cannot invoke "net.minecraft.world.level.Level.m_8055_(net.minecraft.core.BlockPos)" because "worldIn" is null" 

We've tried restarting the clients, server etc but still no joy.

**Comment by AllenSeitz** [comment]
Thank you for the report. This is a previously unheard of issue.

I've tested myself in a dedicated server environment with a few other mods installed and it does work for me. Can I see a whole logfile please? I'm mainly interested in which other mods are installed. Because that error alone seems to indicate that dimdungeons:dhungeon_dimension wasn't registered or otherwise somehow doesn't exist.

**Comment by LidorPrototype** [comment]
For me there is no error text, it just wont activate the portal no matter what I di

**Comment by AllenSeitz** [comment]
I'm sorry to reply to this so late. But did version 1.13.4 of this mod fix the issue for you? I did fix something that could cause this.

**Comment by AllenSeitz** [comment]
If this is still happening in 1.18.2 you can make a new ticket or let me know however you want. I assume it's working now?
