### ISSUE TITLE
Keys generating from keystones = crash

### ISSUE THREAD

**Issue by Zaetriks** [AllenSeitz/DimDungeons#43]
Has happened twice to me where I grab a key from a keystone it causes my game to crash it generates the key but it causes a crash, no clue if this a memory issue, as it DOES generate the key but crashes my game.

**Comment by AllenSeitz** [comment]
Which version of the mod and Minecraft? I'm glad the key is still there when you reload the world (or server? is this a multiplayer server by any chance?) but it shouldn't be crashing.

**Comment by AllenSeitz** [comment]
I may finally have found the issue and a potential fix. Go into the server config and change this setting:

worldborderToRespect = "minecraft:overworld"

If it was set to dimdungeons:dungeon_dimension then change it to minecraft:overworld. Does that solve your problem? If it does I would love to hear it.

**Comment by AllenSeitz** [comment]
I received a new report about this issue.

Does the issue only occur on End Portal Frames which used to contain an eye? (That you previously removed with a key, and made empty again?) If so, holding the right mouse button down for longer might solve the issue.

As well, using an End Portal Frame that never contained an eye or using the alternate Key Inscribing Station should also be glitch free. The issue seems to be something with the "crowbar" function not working or not synchronizing correctly.

**Comment by AllenSeitz** [comment]
Fixed in the latest release! Download v172 and let me know if the issue still isn't fixed.
