### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by Catomax262** [AllenSeitz/DimDungeons#48]
https://crashy.net/YFd1VmlCrFVz2Z19M4fN

**Comment by AllenSeitz** [comment]
Thank you! Which version of MC and this mod did the crash occur on?

That error is strange. Because 650 is clearly right there at the end of the allowed values list. But I will look into this.

**Comment by AllenSeitz** [comment]
That makes sense. According to the call stack it did crash when transitioning the keyhole from the ticking state to the non-ticking state. I have a potential fix in the works already.

**Comment by AllenSeitz** [comment]
Does this happen every time, reliably? Or just once or sometimes? I couldn't replicate it but I could see where the problem might have been in the code.

**Comment by AllenSeitz** [comment]
I believe that version 166 which I am about to upload to Curseforge in the next 5 minutes will fix this.

Thank you for your reports!

**Comment by david-why** [comment]
Thanks for the quick update!

I can't test if the patch fixes the problem because other mods our server is using do not currently support new Forge versions (or at least I think so). That's why our server is still running on 41.0.45 :-( Maybe I'll check the other mods out and see if they upgraded.

**Comment by MattB70** [comment]
Different error, but same reproduction steps.
**1.18.2
dimdungeons-166-forge-1.18.2**
Server log: https://gist.github.com/MattB70/20f706809e509c705db4f3451222fa6f
Client logged nothing of value

Player report:
![image](https://user-images.githubusercontent.com/43189368/185532083-91530a1b-3e46-42fb-8e72-a903a73d1ad4.png)

**Comment by AllenSeitz** [comment]
I know this one! It's a different issue but it is one that has been reported before.

The mod is trying to nametag a mob, but the mob was null because it wasn't allowed to spawn. For the person who reported the issue the problem was another mod "Bad Mobs" that was enforcing a sort of ban list on the modpack. The fix was to go into the dimdungeons config and remove or replace the banned mobs with something else. (Which the modpack designer should have done, but they didn't test.)
