### ISSUE TITLE
Unable to load world after removing Dimensional Dungeons

### ISSUE THREAD

**Issue by laserlemons** [AllenSeitz/DimDungeons#52]
The following error occurs when trying to load a world after removing Dimensional Dungeons from the mod list:

https://gist.github.com/laserlemons/28db47cd54604696f08c5fd56ee09d4a

**Comment by AllenSeitz** [comment]
I'm sorry for the late reply. Thank you for attaching a log!

Removing mods that add custom dimensions is known to be buggy. This is actually a vanilla problem and it's one of the big dangers that Mojang is warning you about when they say "Here Be Dragons" on that annoying warning screen. In this case I think some other mod might technically be at fault but that's not important.

Since removing custom dimensions and biomes is dangerous I recommend 1) not, and instead casually banning the mod (which is easier with DimDungeons than some other mods) 2) removing the mod but re-adding the dimensions, dimension types, and biomes in a datapack. This will keep the registry unchanged.

The second option is not too difficult to do if you're familiar with datapacks. Basically you can unzip my mod, grab the json files for the dimensions and biomes, and use them without using the rest of the mod. This will fix the registry problem you're having. Here's specific instructions.

https://github.com/AllenSeitz/DimDungeons/wiki/Datapacks-for-Dummies
