### ISSUE TITLE
[1.19.2] Crash with Canary

### ISSUE THREAD

**Issue by Sazuzaki** [AllenSeitz/DimDungeons#63]
Happens when putting a key into the key block
https://pastebin.com/Zhxfyt0d

**Comment by AllenSeitz** [comment]
Thank you. I'll keep this open and investigate it when I next update the 1.19.2 version.

From a quick look, it looks like you were in the middle of building a dungeon, and specifically a room that contained Redstone Comparitors. (Which is tons of them, I wish I knew which.) From there at least three mixins modify vanilla behavior: Oculus, Supplementaries, and Canary. 

The crash ultimately happened in Canary and I'm tempted to put the blame there because I've tested with Supplementaries. It could be that I'm the only person in the whole world who uses Comparitors in Structure Blocks and there is a case they haven't considered with their optimizations. It could also be a combination of the mixins.

I recommend reporting this crash to the Canary team too. Especially if removing Canary resolves the crash. It's possible that the fault is with Dimensional Dungeons but I don't see how. 

In the server config for this mod you can change the logLevel to 'all' and that will tell you which room crashed, at least.

**Comment by Sazuzaki** [comment]
Sure thing, sorry for the late response. Thanks for telling me about the logLevel, and the crash has been reported to Canary as well.

**Comment by AllenSeitz** [comment]
My backport to 1.19.2 (technically 1.19.0) has been started. Soon you'll have a newer version of Dimensional Dungeons to test with. Although I don't think anything I've changed or added will affect this issue.

**Comment by Sazuzaki** [comment]
Oh sounds good man, and don't worry, the crash with Canary was fixed in the latest update today. Thanks for the hard work Allen, you made one of my favorite mods, and your support for it is no less the amazing.
