### ISSUE TITLE
[Suggestion] Possibly use PersistenceRequired instead of nametags

### ISSUE THREAD

**Issue by MarioSMB** [AllenSeitz/DimDungeons#70]
I must confess that I do not know the technical aspects of this mechanic, just that mobs with the PersistenceRequired boolean tag are not supposed to despawn, as mentioned here: https://gaming.stackexchange.com/a/241707  
Just putting it out there incase this would allow you to include mobs in the dungeons without naming them!

**Comment by AllenSeitz** [comment]
Thank you for the suggestion!

You're right that originally (1.14) I think I did name the mobs to prevent them from despawning. Although now I do it as a stylistic choice. Enemies in the advanced dungeons are given special names to show that they have modified stats and potion buffs.

And as far as I know, I do set PersistenceRequired on all mobs. Because it is also possible to customize which mobs appear and those mobs may not have custom names.

**Comment by AllenSeitz** [comment]
If you see a mob with persistenceRequired=true, let me know. It should be in all versions going back to 1.18.2 at least.
