### ISSUE TITLE
 Advanced Dimensional Dungeons Portal Crashes When Used

### ISSUE THREAD

**Issue by NillerMedDild** [AllenSeitz/DimDungeons#8]
Relayed from Enigmatica 4's issue tracker: https://github.com/NillerMedDild/Enigmatica4/issues/365

### Issue
After constructing the advanced dimensional dungeons portal and inserting an advanced (read: green colored) key the server crashes. Upon restart the server has opened the portal but only one block is active (see picture). The portal is functional after restart and allows the player to travel to the dungeon with no further issue. Removing the key is fine also. Inserting a basic (read: tan colored) key works with no problems with this setup.

### Logs
Crash Report:
https://pastebin.com/raw/f3tzQcYa

### Versions
- Forge-1.14.4-28.2.3
- dimdungeons-1.051-forge-1.14.4

Portal after restart
![billede](https://user-images.githubusercontent.com/21295394/79036443-8d266200-7bc8-11ea-9b8e-f88d47b987e1.png)

**Comment by AllenSeitz** [comment]
Thank you for the report. I'm afraid that the method TileEntityBanner.getPatternList() is client side only. I ran into this problem while porting to 1.15 and I'm surprised that it didn't bite me sooner, since I definitely ran a 1.14 server for my friends. I'll change my 1.14 implementation in version 1.06.

**Comment by Pixelmnkey** [comment]
Just had the same crash, can we expect a fix for 1.14.4? Lovely mod !

**Comment by AllenSeitz** [comment]
Fixed in 1.06
