### ISSUE TITLE
Key not working on the endportalblock and Portal Keystone.

### ISSUE THREAD

**Issue by HandsomeYDZ** [AllenSeitz/DimDungeons#80]
Sory for my pool English, hope you can understand.
The first is I run this mod on a server and the server core is MohistMc 1.18.2 v882.
I also install EssentialX and Luckperms in my server plugins.

And the problem is that I cant transform blank key to a portable key or I can not put the portable key on a Portal Keystone or put it off. 

But when i try to be an OP( just type /op ***** ), it works!
so I tried to search how to set the permission but I still dont know how to deal with it.
It seem's like the permission plugin block my interaction with the key, how can I solve it without deleting luckperms and essentialx?

There is another problem that it always printout a message in Terminal after interacting with a protal keystone in OP⬇️⬇️

"CONSOLE issued server command: /item modify entity lingjiuforever(just a username) weapon.mainhand dimdungeons:add_used"
"error: Only Player in the game can use item"
should I ingore it?

**Comment by AllenSeitz** [comment]
Your English is good! Thank you for the report.

This does seem like an issue with Luckperms denying the block interaction needed to activate the key. I hope that plugin has some way to configure exceptions? But I am unfamiliar with Luckperms so I am unable to assist you with using that plugin.

One last thing to try if you are unable to configure Luckperms is to try using an End Portal Frame instead. It just might work.

Lastly, I believe you can ignore that print statement in the terminal. But thank you for including it because it could have been helpful.

**Comment by HandsomeYDZ** [comment]
Thank you very much! I'll try it later.
